module.exports = [
  { id: 1, name: 'js' },
  { id: 2, name: 'javascript' },
  { id: 3, name: 'angular' },
  { id: 4, name: 'react' },
  { id: 5, name: 'reactdom' },
  { id: 6, name: 'react native' },
  { id: 7, name: 'python' },
  { id: 8, name: 'machine learning' },
  { id: 9, name: 'ruby' },
  { id: 10, name: 'android' },
  { id: 11, name: 'ios' },
  { id: 12, name: 'sql' },
  { id: 13, name: 'java' },
  { id: 14, name: '.net' },
  { id: 15, name: 'laravel' },
  { id: 16, name: 'php' },
  { id: 17, name: 'cordovo' },
  { id: 18, name: 'unity' },
  { id: 18, name: 'unity3d' },
  { id: 19, name: 'vue.js' },
];
